service: basketcase

build:
  esbuild:
    bundle: true
    minify: true

provider:
  name: aws
  profile: taylorjg
  runtime: nodejs18.x
  environment:
    BONSAI_URL: ${env:BONSAI_URL}
  httpApi:
    cors: true

functions:
  search:
    handler: src/search.handler
    events:
      - httpApi:
          method: post
          path: /api/search
