frameworkVersion: '3'
org: taylorjg
app: basketcase
service: basketcase

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    BONSAI_URL: ${param:bonsaiUrl}

plugins:
  - serverless-webpack

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello
