frameworkVersion: '3'
org: taylorjg
app: basketcase
service: basketcase

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    BONSAI_URL: ${param:bonsaiUrl}

plugins:
  - serverless-webpack

functions:
  search:
    handler: src/search.handler
    events:
      - httpApi:
          method: post
          path: /api/search
